<html>
<body>
Informa sobre llamadas al método <code>super.tearDown()</code> de JUnit 3 que no se ejecutan dentro de un bloque <code>finally</code>.
Si se lanza una excepción antes de llamar a <code>super.tearDown()</code>, podría causar inconsistencias y pérdidas de recursos.
<p><b>Ejemplo:</b></p>
<pre><code lang="java">
  public class AnotherTest extends CompanyTestCase {
    private Path path;
    @Override
    protected void setUp() throws Exception {
      super.setUp();
      path = Files.createTempFile("File", ".tmp");
    }
    @Override
    protected void tearDown() throws Exception {
      Files.delete(path);
      super.tearDown();
    }
  }
</code></pre>
<p>Código mejorado:</p>
<pre><code lang="java">
  public class AnotherTest extends CompanyTestCase {
    private Path path;
    @Override
    protected void setUp() throws Exception {
      super.setUp();
      path = Files.createTempFile("File", ".tmp");
    }
    @Override
    protected void tearDown() throws Exception {
      try {
        Files.delete(path);
      } finally {
        super.tearDown();
      }
    }
  }
</code></pre>
</body>
</html>
