Jupyter.remote.add.dialog.ok.button.text=Añadir
Jupyter.remote.add.dialog.title=Nuevo Jupyter
Jupyter.remote.add.option.discovered.local=Conectar con un servidor Jupyter local en ejecución
Jupyter.remote.add.option.managed.local=Iniciar un servidor Jupyter local
Jupyter.remote.add.option.url=Conectar a un servidor Jupyter mediante una URL
Jupyter.remote.copying=Copiando ''{0}'' a ''{1}''...
Jupyter.remote.copying.multiple=Copiando múltiples archivos a ''{0}''...
Jupyter.remote.failed.to.load.remote=Error al cargar archivo remoto
Jupyter.remote.managed.working.directory.title=Directorio de trabajo de Jupyter
Jupyter.remote.refactoring.rename=Renombrar
Jupyter.remote.refactoring.rename.directory=Renombrar directorio
Jupyter.remote.refactoring.rename.file=Renombrar archivo
Jupyter.remote.refactoring.rename.notebook=Renombrar notebook
Jupyter.remote.refactoring.renaming.to=Renombrar ''{0}'' a:
Jupyter.remote.reload.file.from.server.all.files.are.up.to.date=Todos los archivos están actualizados
Jupyter.remote.reload.file.from.server.dialog.checkbox.remember.my.choice=Recordar mi elección(&R)
Jupyter.remote.reload.file.from.server.dialog.question=Existe una versión más reciente de {0} en el servidor. ¿Desea sobrescribir la copia local con ella?
Jupyter.remote.reload.file.from.server.dialog.title=¿Reemplazar el archivo local con el remoto?
Jupyter.remote.reload.file.from.server.number.of.files.reloaded={0,choice,1#{0} archivo|2#{0} archivos} actualizados
Jupyter.remote.remove.connection.confirmation=¿Estás seguro de que deseas eliminar la conexión con {0}?
Jupyter.remote.remove.multiple.files=¿Eliminar {0} archivos remotos?
Jupyter.remote.server.is.unreachable=Servidor no alcanzable
Jupyter.remote.unable.to.create.target.dir=No se puede crear el directorio de destino ''{0}''
Jupyter.remote.unknown.remote.file.status.copying.aborted=No se pudo verificar si existe el archivo remoto ''{0}''. El proceso de copiado se abortó.
Jupyter.remote.url=URL del servidor:
Jupyter.remote.url.discovered.local.combobox=Selecciona un servidor Jupyter local en ejecución:
Jupyter.remote.url.discovered.no.servers=<ningún servidor>
Jupyter.remote.url.managed.local.directory=Directorio de área de trabajo:
Jupyter.remote.verify.cant.create.path=La ruta provista es inválida
Jupyter.remote.verify.managed.empty.path=El directorio de trabajo de Jupyter no puede estar vacío
Jupyter.remote.verify.managed.not.absolute=La ruta debe ser absoluta
Jupyter.remote.verify.managed.not.directory=La ruta proporcionada no es una ruta de directorio
Jupyter.remote.verify.managed.wrong.path=La ruta contiene caracteres incorrectos
Jupyter.remote.verify.url.check.cancelled=Se canceló la comprobación
Jupyter.remote.verify.url.connecting=Comprobando conexión de Jupyter...
Jupyter.remote.verify.url.connection.error=Error de conexión
Jupyter.remote.verify.url.empty=La URL de Jupyter no puede estar vacía
Jupyter.remote.verify.url.malformed=URL inválida. Proporciona una URL de Jupyter como http://my.jupyter.org:8888
Jupyter.remote.verify.url.not.jupyter=No se puede acceder al servidor de Jupyter mediante la URL
Jupyter.remote.verify.url.unexpected.error=Error inesperado
Jupyter.remote.verify.url.wrong.response=Error de conexión a Jupyter. Código de error: {0}, mensaje: {1}
action.AddRemoteJupyter.text=Añadir conexión a Jupyter…
action.ReconnectToRemoteJupyter.text=Reconectar...
action.ReloadRemoteFileAction.description=Volver a cargar los últimos cambios desde el servidor
action.ReloadRemoteFileAction.text=Volver a cargar desde el servidor...
notification.group.jupyter.remote=Notebooks remotos de Jupyter